todoList/urls.py
from django.urls.conf import path
from todoList import views

app_name = 'todoList'

urlpatterns = [
    path('',      views.TodoListView.as_view(), name="home-todo"),
    path("lista/", views.TodoListView.as_view(), name="lista-todo"),
    path("cria/", views.TodoCreateView.as_view(), name="cria-todo"),
    path("atualiza/<int:pk>", views.TodoUpdateView.as_view(), name="atualiza-todo"),
    path("apaga/<int:pk>", views.TodoDeleteView.as_view(), name="apaga-todo"),
    path('lista/minhasAtividades/', views.minhasAtividades, name="todo-minhasAtividades"),
    path('minhaLista/', views.AuthorListView.as_view(), name="todo-minhaLista"),

]

trabalho2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views
from django.contrib.auth.views import LoginView,LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView,PasswordResetConfirmView, PasswordResetCompleteView
from django.urls.base import reverse_lazy
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import User

urlpatterns = [
    path('', views.homeSec, name="sec-home"),
    path('admin/', admin.site.urls),
    path('todo/', include('todoList.urls')),
    path('accounts/', views.homeSec, name="sec-home"),
    path('accounts/registro', views.registro, name="sec-registro"),
    path('accounts/login/', LoginView.as_view(template_name="registro/login.html"), name="sec-login"),
    path('accounts/logout/', LogoutView.as_view(next_page=reverse_lazy('sec-home')), name="sec-logout"),
    path('accounts/profile/', views.homeSec, name="sec-home"),
    path('accounts/passwordChange/', PasswordChangeView.as_view(template_name="registro/password_change_form.html",
    success_url=reverse_lazy('sec-passwordChangeDone')), name="sec-passwordChange"),

    path('accounts/passwordChangeDone/', PasswordChangeDoneView.as_view(template_name="registro/password_change_done.html"),
     name="sec-passwordChangeDone"),

    path('accounts/updateProfile/<int:pk>', UpdateView.as_view(
    template_name="registro/updateProfile.html",
    success_url=reverse_lazy("sec-home"), model=User, fields=['first_name', 'last_name', 'email']),
     name="sec-updateProfile"),


     path('account/passwordReset', PasswordResetView.as_view(
         template_name="registro/password_reset_form.html",
         success_url=reverse_lazy("sec-passwordResetDone"),
         from_email="guparagua@gmail.com",
         subject_template_name="registro/password_reset_subject.txt",
         html_email_template_name="registro/password_reset_email.html"
     ),
     name="sec-passwordReset"),

     path('account/passwordResetDone', PasswordResetDoneView.as_view(template_name="registro/password_reset_done.html"),
     name = "sec-passwordResetDone"),

     path('account/passwordResetConfirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name="registro/password_reset_confirm.html",
            success_url=reverse_lazy("sec-passwordResetComplete")
        ),
         name="password_reset_confirm"),

     path('accounts/passwordResetComplete/', PasswordResetCompleteView.as_view(
        template_name='registro/password_reset_complete.html'
     ), name='sec-passwordResetComplete'),


     path('accounts/verificaUsername', views.verificaUsername, name="sec-verificaUsername"),



    # path('', views.home, name='home'),
]

trabalho2/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse

def homeSec(request):
    return render(request, "registro/homeSec.html")

'''
permite criar um usuario
GET -> cria o formulario para criar usuario
POST -> pega os dados do formulario e cria um usuario
'''
def registro(request):
    if request.method == 'POST':
        #cria usuario
        formulario = UserCreationForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('sec-home')
        else:
            context = {'form': formulario,}
            return render(request,"registro/registro.html", context)
    else:
        #mostra o formulario
        formulario = UserCreationForm()
        context = {'form': formulario,}
        return render(request,"registro/registro.html", context)

@login_required
def paginaSecreta(request):
    return render(request, "registro/paginaSecreta.html")

'''
Recebe um pedido de verificacao com um username
Procurar no banco de dados o verificaUsername

'''

def verificaUsername(request):
    #GET --> dicionario com todos os campos do formulario
    username = request.GET.get('username', None)
    existe = User.objects.filter(username__iexact=username).exists()
    resposta = {
        "existe": existe,
        "mensagem": "Esse usuario já existe" if existe else "Esse usuario nao existe",
        "cor": "#FF0000" if existe else "#FFFFFF"
    }
    return JsonResponse(resposta)

trabalho2/templates/registro/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="../../static/MeuSite/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
    {% block head %}{% endblock %}
  </head>
  <body style="background-color: #F6F7FB!important;">

    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #FFFFFF!important;">
      <a class="navbar-brand" href="#">Nebular</a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarColor01">
        <ul class="navbar-nav mx-5">
          <li class="nav-item active mr-2">
            <a href="{% url 'sec-home' %}">Home</a>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% if user.is_authenticated %}

          <li class="nav-item mr-2">
            <a href="{% url 'todoList:cria-todo' %}">Cria Atividades</a>
          </li>
          <li class="nav-item mr-2">
            <a href="{% url 'todoList:lista-todo' %}">Lista Atividades</a>
          </li>
          <li class="nav-item mr-2">
            <a href="{% url 'todoList:todo-minhaLista' %}">Minhas Atividades</a>
          </li>
          <li class="nav-item dropdown mr-2">
            <a class="dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown">
              Perfil
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'sec-updateProfile' pk=user.id %}">Update Perfil</a>
              <a class="dropdown-item" href="{% url 'sec-passwordChange' %}">Troca Senha</a>
            </div>
          </li>
          <li class="nav-item mr-2">
            <a href="{% url 'sec-logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item mr-2">
            <a href="{% url 'sec-registro' %}">Registro</a>
          </li>
          <li class="nav-item mr-2">
            <a href="{% url 'sec-login' %}">Login</a>
          </li>

        </ul>
        {% endif %}
        Voce é {% firstof user.first_name user.username "visitante" %}
      </div>
    </nav>

    <div class="mt-4" style="background-color: #F6F7FB!important;">
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

trabalho2/templates/registro/homeSec.html
{% extends 'registro/base.html' %}

{% block title %} Homepage de Controle de Acesso {%endblock %}

{% block content %}


  <div class="container">
    <h2 class="text-center">Pagina Inicial </h2>


    <div class="row">



    <div class="col-sm card text-white bg-primary mr-3" style="max-width: 20rem; background-color: #CEDFFA !important;">
      <div class="card-header">Atividades Públicas</div>
      <div class="card-body">
        <p class="card-text"> Ver Atividades públicas de todos os usuários</p>
        <a style="color: black;" href="{% url 'todoList:lista-todo' %}"> Clique aqui </a>

      </div>

    </div>

    <div class="col-sm card text-white bg-info mr-3" style="max-width: 20rem; background-color: #FCECCD !important;">
      <div class="card-header">Minhas Atividades</div>
      <div class="card-body">
        <p class="card-text"> Ver minhas Atividades</p>
        <a style="color: black;" href="{% url 'todoList:todo-minhaLista' %}"> Clique aqui </a>

      </div>

    </div>

    <div class="col-sm card text-white bg-success mr-3" style="max-width: 20rem; background-color: #FDB2B9 !important;">
      <div class="card-header">Nova Atividade</div>
      <div class="card-body">
        <p class="card-text"> Criar Nova Atividade</p>
        <a style="color: black;" href="{% url 'todoList:cria-todo' %}"> Clique aqui </a>
      </div>
    </div>

  </div>
</div>
{%endblock%}

trabalho2/templates/registro/login.html
{% extends 'registro/base.html' %}

{% block title %} Login  {%endblock %}

{% block content %}

  <h2>Entre com seus dados para fazer login </h2>
  <form class=""  method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Login">
  </form>

  Esqueceu a senha? Clique <a href="{% url 'sec-passwordReset' %}">aqui</a> |

{%endblock%}

trabalho2/templates/registro/paginaSecreta.html
{% extends 'registro/base.html' %}

{% block title %} Pagina Secreta {%endblock %}

{% block content %}

  <h2>Pagina Secreta </h2>
  {% lorem 3 p %}


{%endblock%}

trabalho2/templates/registro/password_change_done.html
{% extends 'registro/base.html' %}

{% block title %} Troca Senha OK  {%endblock %}

{% block content %}

  <h2>Senha trocada com sucesso </h2>

{%endblock%}

trabalho2/templates/registro/password_change_form.html
{% extends 'registro/base.html' %}

{% block title %} Troca Senha  {%endblock %}

{% block content %}

  <h2>Entre com seus dados para trocar senha </h2>
  <form class=""  method="post">
    {% csrf_token %}
    <!-- casa: formato tabela -->
    {{form.as_p}}
    <input type="submit" value="Confirmar">
  </form>
{%endblock%}

trabalho2/templates/registro/password_reset_complete.html
{% extends 'registro/base.html' %}

{% block title %}Senha Criada{% endblock %}

{% block content %}

  <h2>Senha Criada</h2>
  <p>Senha criada com sucesso!</p>
  <p>Click
  <a href="{% url 'sec-login' %}?next={% url 'sec-home %}">
  aqui</a> para fazer login.</p>
{% endblock %}

trabalho2/templates/registro/password_reset_confirm.html
{% extends 'registro/base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

{% endblock %}

{% block title %} Recupere a senha  {%endblock %}

{% block content %}

  <h2>Entre com uma nova senha </h2>
  <form class=""  method="post">
    {% csrf_token %}

    <table>
      {{form.as_table}}
    </table>

    <input type="submit" value="Confirmar">
  </form>

{%endblock%}

trabalho2/templates/registro/password_reset_done.html
{% extends 'registro/base.html' %}

{% block title %} Password Reset Done  {%endblock %}

{% block content %}

  <h2>Email enviado </h2>

{%endblock%}

trabalho2/templates/registro/password_reset_email.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Recuperacao de senha perdida</title>
  </head>
  <body>

    Olá, {{user.username}}<br>
    Você solicitou a redefinicao da sua senha. Configure uma nova
    <a href="{{ protocol }}://{{domain}}{%url 'password_reset_confirm' uidb64=uid token=token %}"> aqui</a>
    <br>
    Obrigada, {{domain}}
  </body>
</html>

trabalho2/templates/registro/password_reset_form.html
{% extends 'registro/base.html' %}

{% block title %} Reset Senha  {%endblock %}

{% block content %}

  <h2>Entre com seu email para resetar sua senha </h2>
  <form class=""  method="post">
    {% csrf_token %}
    <!-- casa: formato tabela -->
    {{form.as_p}}
    <input type="submit" value="Confirmar">
  </form>
{%endblock%}

trabalho2/templates/registro/registro.html
{% extends 'registro/base.html' %}
{% load static %}

{% block title %} Cadastro de Usuario {%endblock %}

{% block head %}
<script type="text/javascript" src="{% static 'Registro/js/registro.js' %}">

</script>
{% endblock %}

{% block content %}

  <h2>Entre com seus dados </h2>
  <div class="" id="idErro">
    &nbsp;
  </div>
  <form class=""  method="post">
    {% csrf_token %}
    <!-- casa: formato tabela -->
    {{form.as_p}}
    <input type="submit" value="Cria Usuario">
  </form>
{%endblock%}

trabalho2/templates/registro/updateProfile.html
{% extends 'registro/base.html' %}

{% block title %} Update Perfil  {%endblock %}

{% block content %}

  <h2>Entre com seus dados para atualizar seu perfil </h2>
  <form class=""  method="post">
    {% csrf_token %}
    <!-- casa: formato tabela -->
    {{form.as_p}}
    <input type="submit" value="Salvar">
  </form>
{%endblock%}