todoList/urls.py
from django.urls.conf import path
from todoList import views

app_name = 'todoList'

urlpatterns = [
    path('',      views.TodoListView.as_view(), name="home-todo"),
    path("lista/", views.TodoListView.as_view(), name="lista-todo"),
    path("cria/", views.TodoCreateView.as_view(), name="cria-todo"),
    path("atualiza/<int:pk>", views.TodoUpdateView.as_view(), name="atualiza-todo"),
    path("apaga/<int:pk>", views.TodoDeleteView.as_view(), name="apaga-todo"),
    path('lista/minhasAtividades/', views.minhasAtividades, name="todo-minhasAtividades"),
    path('minhaLista/', views.AuthorListView.as_view(), name="todo-minhaLista"),

]

trabalho2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views
from django.contrib.auth.views import LoginView,LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView,PasswordResetConfirmView, PasswordResetCompleteView
from django.urls.base import reverse_lazy
from django.views.generic.edit import UpdateView
from django.contrib.auth.models import User

urlpatterns = [
    path('', views.homeSec, name="sec-home"),
    path('admin/', admin.site.urls),
    path('todo/', include('todoList.urls')),
    path('accounts/', views.homeSec, name="sec-home"),
    path('accounts/registro', views.registro, name="sec-registro"),
    path('accounts/login/', LoginView.as_view(template_name="registro/login.html"), name="sec-login"),
    path('accounts/logout/', LogoutView.as_view(next_page=reverse_lazy('sec-home')), name="sec-logout"),
    path('accounts/profile/', views.homeSec, name="sec-home"),
    path('accounts/passwordChange/', PasswordChangeView.as_view(template_name="registro/password_change_form.html",
    success_url=reverse_lazy('sec-passwordChangeDone')), name="sec-passwordChange"),

    path('accounts/passwordChangeDone/', PasswordChangeDoneView.as_view(template_name="registro/password_change_done.html"),
     name="sec-passwordChangeDone"),

    path('accounts/updateProfile/<int:pk>', UpdateView.as_view(
    template_name="registro/updateProfile.html",
    success_url=reverse_lazy("sec-home"), model=User, fields=['first_name', 'last_name', 'email']),
     name="sec-updateProfile"),


     path('account/passwordReset', PasswordResetView.as_view(
         template_name="registro/password_reset_form.html",
         success_url=reverse_lazy("sec-passwordResetDone"),
         from_email="guparagua@gmail.com",
         subject_template_name="registro/password_reset_subject.txt",
         html_email_template_name="registro/password_reset_email.html"
     ),
     name="sec-passwordReset"),

     path('account/passwordResetDone', PasswordResetDoneView.as_view(template_name="registro/password_reset_done.html"),
     name = "sec-passwordResetDone"),

     path('account/passwordResetConfirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name="registro/password_reset_confirm.html",
            success_url=reverse_lazy("sec-passwordResetComplete")
        ),
         name="password_reset_confirm"),

     path('accounts/passwordResetComplete/', PasswordResetCompleteView.as_view(
        template_name='registro/password_reset_complete.html'
     ), name='sec-passwordResetComplete'),


     path('accounts/verificaUsername', views.verificaUsername, name="sec-verificaUsername"),



    # path('', views.home, name='home'),
]

todoList/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Atividade(models.Model):
    # nickname = models.CharField(max_length=30, help_text="entre com o seu nickname")
    autor = models.ForeignKey(User,null=True, on_delete=models.SET_NULL)
    texto = models.CharField(max_length=200,help_text="digite o titulo da atividade")
    prazo = models.DateField(help_text="digite a data da entrega(YYYY-MM-DD)")
    privada = models.BooleanField(default=False)

todoList/forms.py
from todoList.models import Atividade
from django import forms

class AtividadeForm(forms.ModelForm):
    # autor = forms.CharField(required=False, widget=forms.TextInput(attrs={'readonly': 'True'}))
    class Meta:
        model = Atividade
        fields = ['texto', 'prazo', 'privada']

todoList/views.py
from django.shortcuts import render
from todoList.models import Atividade
from todoList.forms import AtividadeForm
from django.views.generic.base import View
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class TodoListView(View):
    def get(self,request,*args, **kwargs):
        todos = Atividade.objects.filter(privada=False)
        context = {'todos': todos, 'minhasAtividades': False }
        return render(request, 'todoList/listaTodo.html', context)

@login_required()
def minhasAtividades(request):

    todosAutor = Atividade.objects.filter(autor=request.user).values()
    todosAutor = list(todosAutor)
    data = {
        'data': todosAutor,
    }
    return JsonResponse(data,)

class AuthorListView(LoginRequiredMixin,View):
    def get(self,request,*args, **kwargs):
        todosAutor = Atividade.objects.filter(autor=request.user)
        context = {'todos': todosAutor, 'minhasAtividades': True  }
        return render(request, 'todoList/listaTodo.html', context)

class TodoCreateView(LoginRequiredMixin, View):
    def get(self,request,*args, **kwargs):
        context = {'formulario': AtividadeForm, }
        return render(request, 'todoList/criaTodo.html', context)


    def post(self,request,*args, **kwargs):
        formulario = AtividadeForm(data=request.POST,initial={'autor': request.user.username})
        print(formulario,formulario.is_valid())
        #formulario = dados do POST
        if formulario.is_valid():

            todo = formulario.save()
            todo.autor = request.user
            #salvar no banco
            todo.save()
            #redirecionar para outro view
            return HttpResponseRedirect(reverse_lazy('todoList:lista-todo'))
        else:
            return HttpResponseRedirect(reverse_lazy('todoList:cria-todo'))

class TodoUpdateView(View):

    def get(self,request,pk,*args, **kwargs):
        todo = Atividade.objects.get(pk=pk)
        formulario = AtividadeForm(instance=todo)
        context = {'todo': formulario, }
        return render(request, 'todoList/atualizaTodo.html', context)

    def post(self,request,pk,*args, **kwargs):
        todo = get_object_or_404(Atividade, pk=pk)
        formulario = AtividadeForm(request.POST, instance=todo)

        if formulario.is_valid():
            print('form up')
            todo = formulario.save()
            todo.autor = request.user
            todo.save()
            return HttpResponseRedirect(reverse_lazy('todoList:lista-todo'))
        else:
            context = {'todo': formulario, }
            return render(request, 'todoList/atualizaTodo.html', context)


class TodoDeleteView(View):
    def get(self,request,pk,*args, **kwargs):
        todo = Atividade.objects.get(pk=pk)
        context = {'todo': todo, }
        return render(request, 'todoList/apagaTodo.html',context)

    def post (self,request,pk,*args, **kwargs):
        todo = Atividade.objects.get(pk=pk)
        todo.delete()
        print("Removendo o Todo", pk)
        return HttpResponseRedirect(reverse_lazy("todoList:lista-todo"))

todoList/templates/todoList/apagaTodo.html
{% extends 'registro/base.html' %}

{% block title %} Apaga Item {%endblock %}

{% block content %}

<h1>Remoção de item</h1>
<form method="POST">
  {% csrf_token %}
  Confirma a remoção de: {{ todo.texto }} ({{todo.prazo}})?<br>

    <a href="{% url 'todoList:lista-todo' %}"class="btn btn-primary" >Cancela</a>
    <button type="submit" class="btn btn-danger">Confirmar</button>

</form>
{%endblock%}

todoList/templates/todoList/atualizaTodo.html
{% extends 'registro/base.html' %}

{% block title %} Lista de Todo {%endblock %}

{% block content %}

<h1>Atualização de item</h1>
<form class="" action="" method="post">
  {% csrf_token %}
  <table>
    {{todo.as_table}}
  </table>
  <button type="submit">Atualiza</button>
</form>
{%endblock%}

todoList/templates/todoList/criaTodo.html
{% extends 'registro/base.html' %}

{% block title %} Lista de Todos {%endblock %}

{% block content %}

<h1>Página para criar um item</h1>
<form class="" action="" method="post">
  {% csrf_token %}
  <table>
    {{formulario.as_table}}
  </table>
  <button type="submit">Criar Todo</button>
</form>
{%endblock%}

todoList/templates/todoList/listaTodo.html
{% extends 'registro/base.html' %}
{% load static %}
{% block title %} Lista de Contatos {%endblock %}

{% block head %}
<!-- <script type="text/javascript" src="{% static 'todoList/js/todo.js' %}"></script> -->
{% endblock %}

{% block content %}

<table id="tabela" class="table table-hover" border="3" >
  <thead >
    <tr class="table-primary">
      <th scope="col" style="background-color: #4886FF!important;">Autor</th>
      <th scope="col" style="background-color: #4886FF!important;">Data</th>
      <th scope='col' style="background-color: #4886FF!important;">Atividade</th>
      <th scope='col' style="background-color: #4886FF!important;">Privacidade</th>
      <th scope='col' style="background-color: #4886FF!important;">Ações</th>

    </tr>
  </thead>

  {% for todo in todos %}
  <tbody>
    <tr class="table-light">
      <td>{{todo.autor}} </td>
      <td>{{todo.prazo}}</td>
      <td>{{todo.texto}}</td>
      {% if todo.privada %}
      <td>Privada</td>
      {% else %}
      <td> Pública </td>
      {% endif %}


      {% if minhasAtividades %}
      <td>
        <a href="{% url 'todoList:atualiza-todo' pk=todo.id %}" class="btn btn-primary">
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
          </svg>
        </a>
        <a href="{% url 'todoList:apaga-todo' pk=todo.id %}" class="btn btn-danger">
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
          </svg>
        </a>
      </td>
      {% else %}

      <td>Nenhuma ação disponível</td>
      {% endif %}

    </tr>
  </tbody>
  {% empty %}
  <tbody>
    <tr class="tablwe-secondary">
      <th colspan="5">
        Ainda nao tem Atividades cadastrados
      </th>
    </tr>
  </tbody>

  {% endfor %}
</table>

<div class="mb-3">
  <span>Adicionar mais um item:</span>
  <a href="{% url 'todoList:cria-todo' %}">
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
    </svg>
  </a>
</div>

{%endblock%}

todoList/templates/todoList/todo.html
{% extends 'registro/base.html' %}
{% load static %}

{% block title %}Chat{% endblock %}

{% block head %}
<!-- <script type="text/javascript" src="{% static 'chat/chat.js' %}"></script> -->
{% endblock %}

{% block content %}
  <p>
    Voce esta na sala de chat como <b>{{nickname}}</b>
  </p>

  <table id="idTableChat">
    <tr>
      <th>Sem Mensagens</th>
    </tr>
  </table>


  <form method="post">
    {% csrf_token %}
    <table>
      <tr valign="top">
        <td>
          <table>
            {{form.as_table}}
          </table>
        </td>
        <td>
          <input type="submit" value="Enviar">
        </td>
      </tr>
    </table>
  </form>
{% endblock %}